### ISSUE TITLE
Problem with mtree automatic-retention-period

### ISSUE THREAD

**Issue by kafej** [dell/ansible-datadomain#10]
Hi,

Maybe I'm doing something bad but it looks like this is waiting with the prompt for confirmation:

  - name:  Set retention periods for specified MTree.
    dellemc.datadomain.mtree:
        state: set
        mtree-path: /data/col1/a001us043nve001
        retention:
            automatic-retention-period: 7days

**Comment by kafej** [comment]
ping: @kshirs2 / @gk4delltech

**Comment by kshirs2** [comment]
@kafej 
Yes, You are right.. It is waiting for this prompt to complete the changes. Looks like its not supported using the ssh. I will update the documentation to reflect it.

Do you want to enable Automatic Retention Lock on this MTree? (yes|no) [no]:

**Comment by kafej** [comment]
So, my next question will be, how to enable retention lock automatically for future files in that mtree or how to do that per file after file creation?

**Comment by kshirs2** [comment]
As far as I know, you need to enable Automatic Lock retention and set lock retention and Lock delay settings, on mtree to lock file after writing completes. We opened ticket with support few months back to know command or API call to lock file after writing but they said you can not update retention lock for files once they are written to DD if ARL is not enabled. Application like NetWorker, have feature to apply lock after backups.  Hope this  helps.

**Comment by kafej** [comment]
> As far as I know, you need to enable Automatic Lock retention and set lock retention and Lock delay settings, on mtree to lock file after writing completes. We opened ticket with support few months back to know command or API call to lock file after writing but they said you can not update retention lock for files once they are written to DD if ARL is not enabled. Application like NetWorker, have feature to apply lock after backups. Hope this helps.

So there is like no manual "enable" lock of the file after I will update it to the mtree? and there is no way to send "yes" for this "automatic-retention-period" flag?
